### ISSUE TITLE
Turing.jl

### ISSUE THREAD

**Issue by trappmartin** [lsandig/Kirstine.jl#1]
Hi, this looks like an interesting project. As there seem to be some potential synergies with Turing.jl, are there design plans to either use tooling from Turing or have a way to specify prior beliefs through a Turing model?

**Comment by lsandig** [comment]
Hi, thanks for your interest! 

I'd like to keep the package dependencies as light as possible, so I don't have plans to incorporate Turing.jl. For specifying prior beliefs you can basically use anything from which you can draw a a sample. So yes, a Turing model should work here.

If you'd like to discuss this further, I suggest moving to the [project mailing list](https://lists.sr.ht/~lsandig/kirstine-users) since I've enabled issues on this mirror repo only temporarily for the JOSS review process.
